### ISSUE TITLE
Module 10 

### ISSUE THREAD

**Issue by waynegraham** [dhbridge/curriculum#40]
I think the `get_text` function needs a major refactor. I don't think it's very approachable by novice developers. This code could also produce some difficult to find bugs down the road (particularly `find_subjects` which could be either a function or variable name) if this is used as a basis in the future as a starting template for someone doing this.

We're working on a refactor for this that does the same thing...

**Comment by jerielizabeth** [comment]
Much delayed, but the refactor for this is done with the supporting explanations in latest commit 3b765b64a5

Thank you again, @waynegraham and @erochest

**Comment by erochest** [comment]
Glad to help!
